const menLeatherData = [
    {
      id: 1,
      picture: 'https://example.com/leather1.jpg',
      name: 'Leather Jacket',
      price: '$199',
      description: 'A stylish leather jacket for men.',
      ratings: 4.5,
      measurement: 'Size: L',
    },
    {
      id: 2,
      picture: 'https://example.com/leather2.jpg',
      name: 'Leather Belt',
      price: '$49',
      description: 'A high-quality leather belt with a sleek design.',
      ratings: 4.2,
      measurement: 'Length: 36 inches',
    },
    {
      id: 3,
      picture: 'https://example.com/leather3.jpg',
      name: 'Leather Shoes',
      price: '$149',
      description: 'Elegant leather shoes for formal occasions.',
      ratings: 4.7,
      measurement: 'Size: 10',
    },
    {
      id: 4,
      picture: 'https://example.com/leather4.jpg',
      name: 'Leather Wallet',
      price: '$59',
      description: 'A compact leather wallet with multiple card slots.',
      ratings: 4.0,
      measurement: 'Width: 4.5 inches',
    },
    {
      id: 5,
      picture: 'https://example.com/leather5.jpg',
      name: 'Leather Briefcase',
      price: '$299',
      description: 'A professional leather briefcase for business professionals.',
      ratings: 4.8,
      measurement: 'Dimensions: 16" x 12" x 4"',
    },
    {
      id: 6,
      picture: 'https://example.com/leather6.jpg',
      name: 'Leather Boots',
      price: '$169',
      description: 'Stylish leather boots for a rugged look.',
      ratings: 4.3,
      measurement: 'Size: 9',
    },
    {
      id: 7,
      picture: 'https://example.com/leather7.jpg',
      name: 'Leather Messenger Bag',
      price: '$179',
      description: 'A versatile leather messenger bag for everyday use.',
      ratings: 4.6,
      measurement: 'Dimensions: 14" x 11" x 3"',
    },
    {
      id: 8,
      picture: 'https://example.com/leather8.jpg',
      name: 'Leather Gloves',
      price: '$89',
      description: 'Warm and stylish leather gloves for cold weather.',
      ratings: 4.4,
      measurement: 'Size: M',
    },
    {
      id: 9,
      picture: 'https://example.com/leather9.jpg',
      name: 'Leather Backpack',
      price: '$139',
      description: 'A trendy leather backpack for casual outings.',
      ratings: 4.2,
      measurement: 'Dimensions: 12" x 16" x 6"',
    },
    {
      id: 10,
      picture: 'https://example.com/leather10.jpg',
      name: 'Leather Wallet',
      price: '$69',
      description: 'A slim leather wallet with RFID protection.',
      ratings: 4.7,
      measurement: 'Width: 3.5 inches',
    },
    {
      id: 11,
      picture: 'https://example.com/leather11.jpg',
      name: 'Leather Jacket',
      price: '$249',
      description: 'A premium leather jacket with a timeless design.',
      ratings: 4.9,
      measurement: 'Size: XL',
    },
    {
      id: 12,
      picture: 'https://example.com/leather12.jpg',
      name: 'Leather Briefcase',
      price: '$329',
      description: 'A sophisticated leather briefcase with multiple compartments.',
      ratings: 4.5,
      measurement: 'Dimensions: 15" x 12" x 5"',
    },
    {
      id: 13,
      picture: 'https://example.com/leather13.jpg',
      name: 'Leather Shoes',
      price: '$189',
      description: 'Classic leather shoes for a polished look.',
      ratings: 4.3,
      measurement: 'Size: 11',
    },
    {
      id: 14,
      picture: 'https://example.com/leather14.jpg',
      name: 'Leather Belt',
      price: '$59',
      description: 'A rugged leather belt with antique brass buckle.',
      ratings: 4.1,
      measurement: 'Length: 40 inches',
    },
    {
      id: 15,
      picture: 'https://example.com/leather15.jpg',
      name: 'Leather Messenger Bag',
      price: '$199',
      description: 'A stylish and functional leather messenger bag.',
      ratings: 4.7,
      measurement: 'Dimensions: 16" x 12" x 4"',
    },
    {
      id: 16,
      picture: 'https://example.com/leather16.jpg',
      name: 'Leather Jacket',
      price: '$179',
      description: 'A vintage-style leather jacket for a cool look.',
      ratings: 4.2,
      measurement: 'Size: M',
    },
    {
      id: 17,
      picture: 'https://example.com/leather17.jpg',
      name: 'Leather Wallet',
      price: '$49',
      description: 'A minimalist leather wallet with card slots.',
      ratings: 4.4,
      measurement: 'Width: 4 inches',
    },
    {
      id: 18,
      picture: 'https://example.com/leather18.jpg',
      name: 'Leather Boots',
      price: '$149',
      description: 'Stylish and durable leather boots for any weather.',
      ratings: 4.6,
      measurement: 'Size: 9.5',
    },
    {
      id: 19,
      picture: 'https://example.com/leather19.jpg',
      name: 'Leather Backpack',
      price: '$109',
      description: 'A spacious leather backpack for travel or work.',
      ratings: 4.3,
      measurement: 'Dimensions: 13" x 18" x 7"',
    },
    {
      id: 20,
      picture: 'https://example.com/leather20.jpg',
      name: 'Leather Gloves',
      price: '$79',
      description: 'Classic leather gloves with a soft lining.',
      ratings: 4.5,
      measurement: 'Size: L',
    },
    {
      id: 21,
      picture: 'https://example.com/leather21.jpg',
      name: 'Leather Jacket',
      price: '$299',
      description: 'A premium leather jacket with a modern design.',
      ratings: 4.8,
      measurement: 'Size: XL',
    },
    {
      id: 22,
      picture: 'https://example.com/leather21.jpg',
      name: 'Leather Jacket',
      price: '$299',
      description: 'A premium leather jacket with a modern design.',
      ratings: 4.8,
      measurement: 'Size: XL',
    },
    {
      id: 23,
      picture: 'https://example.com/leather23.jpg',
      name: 'Leather Gloves',
      price: '$59',
      description: 'Stylish leather gloves with touchscreen compatibility.',
      ratings: 4.2,
      measurement: 'Size: M',
    },
    {
      id: 24,
      picture: 'https://example.com/leather24.jpg',
      name: 'Leather Duffel Bag',
      price: '$279',
      description: 'A spacious leather duffel bag for travel or gym.',
      ratings: 4.5,
      measurement: 'Dimensions: 22" x 12" x 10"',
    },
    {
      id: 25,
      picture: 'https://example.com/leather25.jpg',
      name: 'Leather Wallet',
      price: '$39',
      description: 'A slim leather wallet with a money clip.',
      ratings: 4.3,
      measurement: 'Width: 3 inches',
    },
    {
      id: 26,
      picture: 'https://example.com/leather26.jpg',
      name: 'Leather Loafers',
      price: '$129',
      description: 'Comfortable leather loafers for casual wear.',
      ratings: 4.6,
      measurement: 'Size: 9',
    },
    {
      id: 27,
      picture: 'https://example.com/leather27.jpg',
      name: 'Leather Backpack',
      price: '$159',
      description: 'A rugged leather backpack for outdoor adventures.',
      ratings: 4.4,
      measurement: 'Dimensions: 14" x 20" x 8"',
    },
    {
      id: 28,
      picture: 'https://example.com/leather28.jpg',
      name: 'Leather Jacket',
      price: '$349',
      description: 'A premium leather jacket with quilted lining.',
      ratings: 4.8,
      measurement: 'Size: XXL',
    },
    {
      id: 29,
      picture: 'https://example.com/leather29.jpg',
      name: 'Leather Belt',
      price: '$69',
      description: 'A reversible leather belt with a buckle.',
      ratings: 4.1,
      measurement: 'Length: 42 inches',
    },
    {
      id: 30,
      picture: 'https://example.com/leather30.jpg',
      name: 'Leather Gloves',
      price: '$79',
      description: 'Warm and stylish leather gloves for cold weather.',
      ratings: 4.3,
      measurement: 'Size: M',
    },
  ];
  
  export default menLeatherData;
  