const mensSandalLeatherData = [
  {
    id: 1,
    picture: "sandal1.jpg",
    name: "Classic Brown Leather Sandals",
    price: 49.99,
    description: "Premium quality classic brown leather sandals for men.",
    ratings: 4.5,
    measurement: "Available in sizes 7-12",
  },
  {
    id: 2,
    picture: "sandal2.jpg",
    name: "Black Leather Fisherman Sandals",
    price: 39.99,
    description: "Stylish black leather fisherman sandals with adjustable straps.",
    ratings: 4.2,
    measurement: "Available in sizes 6-11",
  },
  {
    id: 3,
    picture: "sandal3.jpg",
    name: "Tan Leather Slide Sandals",
    price: 34.99,
    description: "Comfortable tan leather slide sandals with cushioned insole.",
    ratings: 4.7,
    measurement: "Available in sizes 8-13",
  },
  {
    id: 4,
    picture: "sandal4.jpg",
    name: "Brown Leather Hiking Sandals",
    price: 59.99,
    description: "Durable brown leather hiking sandals for outdoor adventures.",
    ratings: 4.4,
    measurement: "Available in sizes 7-12",
  },
  {
    id: 5,
    picture: "sandal5.jpg",
    name: "Casual Slip-On Leather Sandals",
    price: 29.99,
    description: "Casual slip-on leather sandals with a relaxed and comfortable fit.",
    ratings: 4.0,
    measurement: "Available in sizes 6-11",
  },
  {
    id: 6,
    picture: "sandal6.jpg",
    name: "Black Leather Strappy Sandals",
    price: 44.99,
    description: "Fashionable black leather strappy sandals with a trendy design.",
    ratings: 4.3,
    measurement: "Available in sizes 7-12",
  },
  {
    id: 7,
    picture: "sandal7.jpg",
    name: "Classic Tan Leather Sandals",
    price: 49.99,
    description: "Classic tan leather sandals with a timeless and versatile style.",
    ratings: 4.6,
    measurement: "Available in sizes 8-13",
  },
  {
    id: 8,
    picture: "sandal8.jpg",
    name: "Brown Leather Flip-Flop Sandals",
    price: 19.99,
    description: "Casual brown leather flip-flop sandals for everyday wear.",
    ratings: 3.9,
    measurement: "Available in sizes 6-11",
  },
  {
    id: 9,
    picture: "sandal9.jpg",
    name: "Sports Leather Sandals",
    price: 54.99,
    description: "Sports-inspired leather sandals with adjustable straps and cushioned insole.",
    ratings: 4.5,
    measurement: "Available in sizes 7-12",
  },
  {
    id: 10,
    picture: "sandal10.jpg",
    name: "Comfortable Slip-On Sandals",
    price: 39.99,
    description: "Comfortable slip-on sandals with soft leather and contoured footbed.",
    ratings: 4.2,
    measurement: "Available in sizes 6-11",
  },
  {
    id: 11,
    picture: "sandal11.jpg",
    name: "Stylish Leather Thong Sandals",
    price: 29.99,
    description: "Stylish leather thong sandals with a trendy and fashionable design.",
    ratings: 4.3,
    measurement: "Available in sizes 7-12",
  },
  {
    id: 12,
    picture: "sandal12.jpg",
    name: "Brown Leather Outdoor Sandals",
    price: 59.99,
    description: "Durable brown leather outdoor sandals for hiking and other outdoor activities.",
    ratings: 4.4,
    measurement: "Available in sizes 7-12",
  },
  {
    id: 13,
    picture: "sandal13.jpg",
    name: "Casual Leather Sandals",
    price: 34.99,
    description: "Casual leather sandals with a comfortable fit for everyday use.",
    ratings: 4.1,
    measurement: "Available in sizes 6-11",
  },
  {
    id: 14,
    picture: "sandal14.jpg",
    name: "Black Leather Sport Sandals",
    price: 49.99,
    description: "Black leather sport sandals with adjustable straps and cushioned insole.",
    ratings: 4.7,
    measurement: "Available in sizes 7-12",
  },
  {
    id: 15,
    picture: "sandal15.jpg",
    name: "Stylish Tan Leather Sandals",
    price: 39.99,
    description: "Stylish tan leather sandals with a trendy and fashionable design.",
    ratings: 4.2,
    measurement: "Available in sizes 8-13",
  },
  {
    id: 16,
    picture: "sandal16.jpg",
    name: "Brown Leather Beach Sandals",
    price: 29.99,
    description: "Casual brown leather beach sandals for a relaxed and comfortable style.",
    ratings: 4.4,
    measurement: "Available in sizes 6-11",
  },
  {
    id: 17,
    picture: "sandal17.jpg",
    name: "Leather Slide Sandals",
    price: 34.99,
    description: "Leather slide sandals with a simple and minimalist design.",
    ratings: 4.0,
    measurement: "Available in sizes 7-12",
  },
  {
    id: 18,
    picture: "sandal18.jpg",
    name: "Black Leather Casual Sandals",
    price: 39.99,
    description: "Black leather casual sandals with a comfortable and versatile style.",
    ratings: 4.3,
    measurement: "Available in sizes 8-13",
  },
  {
    id: 19,
    picture: "sandal19.jpg",
    name: "Classic Brown Leather Sandals",
    price: 49.99,
    description: "Classic brown leather sandals with a timeless and versatile style.",
    ratings: 4.6,
    measurement: "Available in sizes 7-12",
  },
  {
    id: 20,
    picture: "sandal20.jpg",
    name: "Tan Leather Flip-Flop Sandals",
    price: 19.99,
    description: "Casual tan leather flip-flop sandals for comfortable everyday wear.",
    ratings: 4.1,
    measurement: "Available in sizes 6-11",
  },
  {
    id: 22,
    picture: "sandal22.jpg",
    name: "Leather Slingback Sandals",
    price: 44.99,
    description: "Leather slingback sandals with a stylish and elegant design.",
    ratings: 4.5,
    measurement: "Available in sizes 7-12",
  },
  {
    id: 23,
    picture: "sandal23.jpg",
    name: "Black Leather Gladiator Sandals",
    price: 54.99,
    description: "Black leather gladiator sandals with multiple straps and buckle closure.",
    ratings: 4.2,
    measurement: "Available in sizes 6-11",
  },
  {
    id: 24,
    picture: "sandal24.jpg",
    name: "Tan Leather Slip-On Sandals",
    price: 39.99,
    description: "Tan leather slip-on sandals for a comfortable and casual style.",
    ratings: 4.7,
    measurement: "Available in sizes 8-13",
  },
  {
    id: 25,
    picture: "sandal25.jpg",
    name: "Brown Leather Mule Sandals",
    price: 49.99,
    description: "Brown leather mule sandals with a trendy and fashionable design.",
    ratings: 4.4,
    measurement: "Available in sizes 7-12",
  },
  {
    id: 26,
    picture: "sandal26.jpg",
    name: "Sports Leather Hiking Sandals",
    price: 59.99,
    description: "Sports-inspired leather hiking sandals for outdoor adventures.",
    ratings: 4.5,
    measurement: "Available in sizes 7-12",
  },
  {
    id: 27,
    picture: "sandal27.jpg",
    name: "Classic Black Leather Sandals",
    price: 49.99,
    description: "Classic black leather sandals with a timeless and versatile style.",
    ratings: 4.6,
    measurement: "Available in sizes 8-13",
  },
  {
    id: 28,
    picture: "sandal28.jpg",
    name: "Brown Leather Fisherman Sandals",
    price: 39.99,
    description: "Brown leather fisherman sandals with adjustable straps.",
    ratings: 4.3,
    measurement: "Available in sizes 7-12",
  },
  {
    id: 29,
    picture: "sandal29.jpg",
    name: "Black Leather Slide Sandals",
    price: 34.99,
    description: "Black leather slide sandals with a comfortable and casual design.",
    ratings: 4.2,
    measurement: "Available in sizes 6-11",
  },
  {
    id: 30,
    picture: "sandal30.jpg",
    name: "Tan Leather Hiking Sandals",
    price: 59.99,
    description: "Tan leather hiking sandals for outdoor adventures and trekking.",
    ratings: 4.7,
    measurement: "Available in sizes 7-12",
  },
]

export default mensSandalLeatherData;
