const cardHoldersData = [
    {
      id: 1,
      picture: "card-holder1.jpg",
      name: "Slim Leather Card Holder",
      price: "$19.99",
      description: "The Slim Leather Card Holder is a minimalist and compact accessory for keeping your cards organized. It is made from genuine leather and features multiple card slots for convenience.",
      ratings: 4.5,
      measurement: "Dimensions: 4 x 3 inches",
    },
    {
      id: 2,
      picture: "card-holder2.jpg",
      name: "Bifold Leather Card Holder",
      price: "$24.99",
      description: "The Bifold Leather Card Holder is a classic and timeless accessory. It is crafted from premium leather and offers multiple card slots, a clear ID window, and a bill compartment.",
      ratings: 4.7,
      measurement: "Dimensions: 4.5 x 3.5 inches",
    },
    {
      id: 3,
      picture: "card-holder3.jpg",
      name: "Zipper Leather Card Holder",
      price: "$29.99",
      description: "The Zipper Leather Card Holder provides extra security for your cards. It features a zip-around closure, multiple card slots, and a coin pocket. Ideal for carrying cards, cash, and coins.",
      ratings: 4.6,
      measurement: "Dimensions: 4.5 x 3.25 inches",
    },
    {
      id: 4,
      picture: "card-holder4.jpg",
      name: "Leather Card Holder with Money Clip",
      price: "$34.99",
      description: "The Leather Card Holder with Money Clip combines functionality and style. It features card slots, an ID window, and a metal money clip for holding cash securely.",
      ratings: 4.8,
      measurement: "Dimensions: 4 x 2.75 inches",
    },
    {
      id: 5,
      picture: "card-holder5.jpg",
      name: "Leather Passport Card Holder",
      price: "$26.99",
      description: "The Leather Passport Card Holder is a versatile accessory for frequent travelers. It can hold multiple cards, a passport, and even some cash. Perfect for keeping all essentials in one place.",
      ratings: 4.5,
      measurement: "Dimensions: 5.5 x 4 inches",
    },
    {
      id: 6,
      picture: "card-holder6.jpg",
      name: "Leather Card Holder with RFID Blocking",
      price: "$31.99",
      description: "The Leather Card Holder with RFID Blocking technology ensures the safety of your cards. It features RFID lining to protect against electronic theft and has multiple card slots for organization.",
      ratings: 4.7,
      measurement: "Dimensions: 4.25 x 3 inches",
    },
    {
      id: 7,
      picture: "card-holder7.jpg",
      name: "Leather Card Holder with Coin Pocket",
      price: "$27.99",
      description: "The Leather Card Holder with Coin Pocket is a practical accessory for everyday use. It has card slots, an ID window, and a zippered coin pocket for storing loose change.",
      ratings: 4.6,
      measurement: "Dimensions: 4.25 x 3.25 inches",
    },
    {
      id: 8,
      picture: "card-holder8.jpg",
      name: "Leather Keychain Card Holder",
      price: "$19.99",
      description: "The Leather Keychain Card Holder is a convenient accessory for keeping your cards accessible. It features card slots and a keyring attachment for easy carrying.",
      ratings: 4.4,
      measurement: "Dimensions: 3.5 x 2.5 inches",
    },
    {
      id: 9,
      picture: "card-holder9.jpg",
      name: "Leather Card Holder with Snap Closure",
      price: "$22.99",
      description: "The Leather Card Holder with Snap Closure is a stylish and secure option for organizing your cards. It features a snap closure, card slots, and a clear ID window.",
      ratings: 4.8,
      measurement: "Dimensions: 4 x 3 inches",
    },
    {
      id: 10,
      picture: "card-holder10.jpg",
      name: "Leather Card Holder with Pull Tab",
      price: "$25.99",
      description: "The Leather Card Holder with Pull Tab allows easy access to your cards. Simply pull the tab to reveal the cards. It also features additional card slots and a clear ID window.",
      ratings: 4.5,
      measurement: "Dimensions: 4 x 2.75 inches",
    },
  ];
  export default cardHoldersData;