const ladiesLeatherBagsData = [
    {
      id: 1,
      image: "bag1.jpg",
      name: "Vintage Leather Tote",
      price: "$149.99",
      description: "The Vintage Leather Tote is a sophisticated and elegant bag crafted from genuine leather. It features a spacious main compartment, interior pockets, and a detachable shoulder strap. Perfect for work or a night out.",
      ratings: 4.8,
      measurement: "Dimensions: 15\" x 12\" x 5\"",
    },
    {
      id: 2,
      image: "bag2.jpg",
      name: "Leather Shoulder Bag",
      price: "$89.99",
      description: "The Leather Shoulder Bag is a stylish and practical accessory for everyday use. It is made from high-quality leather and features an adjustable shoulder strap, multiple compartments, and a sleek design.",
      ratings: 4.5,
      measurement: "Dimensions: 11\" x 9\" x 4\"",
    },
    {
      id: 3,
      image: "bag3.jpg",
      name: "Classic Satchel Bag",
      price: "$119.99",
      description: "The Classic Satchel Bag is a timeless piece that exudes elegance. It is crafted from premium leather and features a structured silhouette, top handle, and a removable crossbody strap for versatility.",
      ratings: 4.7,
      measurement: "Dimensions: 12\" x 10\" x 4\"",
    },
    {
      id: 4,
      image: "bag4.jpg",
      name: "Leather Backpack",
      price: "$109.99",
      description: "The Leather Backpack is a trendy and functional bag that combines style and convenience. It has a spacious main compartment, multiple pockets, adjustable shoulder straps, and a top handle for easy carrying.",
      ratings: 4.6,
      measurement: "Dimensions: 14\" x 12\" x 6\"",
    },
    {
      id: 5,
      image: "bag5.jpg",
      name: "Tassel Crossbody Bag",
      price: "$79.99",
      description: "The Tassel Crossbody Bag is a chic and compact accessory for those who prefer a hands-free option. It features a sleek design, a tassel accent, and an adjustable crossbody strap for a comfortable fit.",
      ratings: 4.4,
      measurement: "Dimensions: 9\" x 7\" x 2\"",
    },
    {
      id: 6,
      image: "bag6.jpg",
      name: "Leather Clutch",
      price: "$69.99",
      description: "The Leather Clutch is a versatile and stylish bag that can be carried as a clutch or used with the detachable wristlet strap. It is made from supple leather and features a secure zip-top closure.",
      ratings: 4.3,
      measurement: "Dimensions: 10\" x 6\" x 1\"",
    },
    {
      id: 7,
      image: "bag7.jpg",
      name: "Structured Tote Bag",
      price: "$139.99",
      description: "The Structured Tote Bag is a sleek and sophisticated option for the modern woman. It is crafted from premium leather and features a structured silhouette, dual top handles, and a spacious interior.",
      ratings: 4.7,
      measurement: "Dimensions: 16\" x 11\" x 5\"",
    },
    {
      id: 8,
      image: "bag8.jpg",
      name: "Leather Hobo Bag",
      price: "$99.99",
      description: "The Leather Hobo Bag is a bohemian-inspired accessory with a relaxed and slouchy silhouette. It is made from soft leather and features a spacious main compartment, a shoulder strap, and fringe accents.",
      ratings: 4.5,
      measurement: "Dimensions: 13\" x 12\" x 4\"",
    },
    {
      id: 9,
      image: "bag9.jpg",
      name: "Mini Crossbody Bag",
      price: "$59.99",
      description: "The Mini Crossbody Bag is a compact and stylish option for those on the go. It features a sleek design, an adjustable crossbody strap, and a zippered front pocket for easy access to essentials.",
      ratings: 4.2,
      measurement: "Dimensions: 8\" x 6\" x 2\"",
    },
    {
      id: 10,
      image: "bag10.jpg",
      name: "Leather Tote with Pockets",
      price: "$129.99",
      description: "The Leather Tote with Pockets is a functional and organized bag for everyday use. It is crafted from durable leather and features multiple exterior pockets, a spacious main compartment, and sturdy handlesfor easy carrying.",
      ratings: 4.6,
      measurement: "Dimensions: 14\" x 11\" x 6\"",
    },
    {
      id: 11,
      image: "bag11.jpg",
      name: "Saddle Crossbody Bag",
      price: "$89.99",
      description: "The Saddle Crossbody Bag is a stylish and compact accessory that adds a touch of bohemian flair to any outfit. It features a saddle-shaped design, an adjustable crossbody strap, and a magnetic closure.",
      ratings: 4.4,
      measurement: "Dimensions: 10\" x 8\" x 3\"",
    },
    {
      id: 12,
      image: "bag12.jpg",
      name: "Leather Bucket Bag",
      price: "$119.99",
      description: "The Leather Bucket Bag is a trendy and spacious bag that combines style and functionality. It features a drawstring closure, an adjustable shoulder strap, and a roomy interior to hold all your essentials.",
      ratings: 4.7,
      measurement: "Dimensions: 12\" x 10\" x 6\"",
    },
    {
      id: 13,
      image: "bag13.jpg",
      name: "Structured Satchel Bag",
      price: "$109.99",
      description: "The Structured Satchel Bag is a timeless and sophisticated accessory for any occasion. It is crafted from premium leather and features a structured silhouette, top handles, and a detachable shoulder strap.",
      ratings: 4.5,
      measurement: "Dimensions: 13\" x 9\" x 4\"",
    },
    {
      id: 14,
      image: "bag14.jpg",
      name: "Leather Tote with Tassel",
      price: "$139.99",
      description: "The Leather Tote with Tassel is a versatile and stylish bag that can be carried for work or leisure. It features a roomy interior, a tassel accent, and comfortable shoulder straps for easy carrying.",
      ratings: 4.6,
      measurement: "Dimensions: 15\" x 12\" x 5\"",
    },
    {
      id: 15,
      image: "bag15.jpg",
      name: "Leather Clutch Wallet",
      price: "$79.99",
      description: "The Leather Clutch Wallet is a compact and organized accessory that can be used as a clutch or a wallet. It features multiple card slots, a zippered coin pocket, and a secure snap closure.",
      ratings: 4.3,
      measurement: "Dimensions: 8\" x 4\" x 1\"",
    },
  ];
  
  export default ladiesLeatherBagsData;
  