const menCasualShoesData = [
    {
      id: 1,
      picture: "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/4c6fbf60-dfc1-44cd-b97c-4502504241eb/air-force-1-07-mens-shoes-5xqQ6q.png",
      name: "Men's Air Force 1",
      price: "$99.99",
      description: "Iconic and versatile shoes with a leather upper and cushioned midsole.",
      ratings: 4.5,
      measurement: "Size 9",
    },
    {
      id: 2,
      picture: "https://www.ubuy.com.bd/productimg/?image=aHR0cHM6Ly9tLm1lZGlhLWFtYXpvbi5jb20vaW1hZ2VzL0kvNjFzWlpvMC1wWkwuX0FDX1VMMTUwMF8uanBn.jpg",
      name: "Men's Stan Smith",
      price: "$89.99",
      description: "Classic tennis-inspired shoes with a smooth leather upper and perforated 3-Stripes.",
      ratings: 4.3,
      measurement: "Size 10",
    },
    {
      id: 3,
      picture: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/374915/02/dt05/fnd/PNA/fmt/png/Suede-Classic-XXI-Men's-Sneakers",
      name: "Men's Suede Classic",
      price: "$79.99",
      description: "Timeless sneakers with a suede upper and rubber outsole for enhanced traction.",
      ratings: 4.7,
      measurement: "Size 9.5",
    },
    {
      id: 4,
      picture: "https://www.converse.com/dw/image/v2/BJJF_PRD/on/demandware.static/-/Sites-cnv-master-catalog-we/default/dwb612ddf8/images/e_08/M9160_E_08X1.jpg?sw=406",
      name: "Converse Chuck Taylor All Star",
      price: "$69.99",
      description: "Iconic high-top sneakers with a canvas upper and rubber toe cap.",
      ratings: 4.2,
      measurement: "Size 10.5",
    },
    {
      id: 5,
      picture: "https://d2ob0iztsaxy5v.cloudfront.net/product/197386/1973867350m8_zm.jpg",
      name: "Vans Old Skool",
      price: "$64.99",
      description: "Skateboarding shoes with a suede and canvas upper and signature sidestripe.",
      ratings: 4.4,
      measurement: "Size 9",
    },
    {
      id: 6,
      picture: "https://i.ytimg.com/vi/XKbe-PA6Gjk/maxresdefault.jpg",
      name: "New Balance Men's 574",
      price: "$79.99",
      description: "Classic running shoes with a suede and mesh upper for breathability.",
      ratings: 4.6,
      measurement: "Size 10",
    },
    {
      id: 7,
      picture: "https://reebok.com.au/cdn/shop/products/14-386413.jpg?v=1666478399",
      name: "Reebok Club C 85",
      price: "$79.99",
      description: "Tennis-inspired shoes with a soft leather upper and low-cut design.",
      ratings: 4.3,
      measurement: "Size 9.5",
    },
    {
      id: 8,
      picture: "https://images-na.ssl-images-amazon.com/images/I/713z6ifPOhL._SLDPMOBCAROUSELAUTOCROP288221_MCnd_AC_SR462,693_.jpg",
      name: "Timberland Men's 6-Inch Premium Boots",
      price: "$149.99",
      description: "Durable and waterproof boots with a leather upper and rugged rubber outsole.",
      ratings: 4.8,
      measurement: "Size 10.5",
    },
    {
      id: 9,
      picture: "https://m.media-amazon.com/images/I/816vQjEO6cL._AC_UY300_.jpg",
      name: "Skechers Men's Equalizer Persistent Sneakers",
      price: "$59.99",
      description: "Comfortable slip-on sneakers with a mesh fabric upper and memory foam insole.",
      ratings: 4.5,
      measurement: "Size 9",
    },
    {
      id: 10,
      picture: "https://cdn.runrepeat.com/storage/gallery/product_primary/35750/asics-gel-kayano-27-black-15915196-720.jpg",
      name: "ASICS Men's Gel-Kayano 27",
      price: "$159.99",
      description: "Premium running shoes with a breathable mesh upper and gel cushioning system.",
      ratings: 4.7,
      measurement: "Size 10",
    },
    {
      id: 11,
      picture: "https://cdn.runningshoesguru.com/wp-content/uploads/2021/04/Under-Armour-Charged-Assert-8-Pair.jpg",
      name: "Under Armour Men's Charged Assert 8",
      price: "$79.99",
      description: "Lightweight and supportive running shoes with a breathable mesh upper.",
      ratings: 4.4,
      measurement: "Size 9.5",
    },
    {
      id: 12,
      picture: "https://www.rei.com/media/2d31ec91-cba9-4021-a5d1-92206156855b.jpg?size=784x588",
      name: "Merrell Men's Moab 2 Vent Hiking Shoes",
      price: "$99.99",
      description: "Versatile hiking shoes with a durable suede and mesh upper and Vibram outsole.",
      ratings: 4.6,
      measurement: "Size 10.5",
    },
    {
      id: 13,
      picture: "https://i5.walmartimages.com/asr/1c315e50-18b9-4bff-aed4-bdacaf0e876b.5b956ce81807a8b592ba95b9a25e774e.jpeg?odnHeight=2000&odnWidth=2000&odnBg=ffffff",
      name: "Salomon Men's Speedcross 5 Trail Running Shoes",
      price: "$129.99",
      description: "Aggressive trail running shoes with a grippy outsole and protective toe cap.",
      ratings: 4.8,
      measurement: "Size 9",
    },
    {
      id: 14,
      picture: "https://columbia.scene7.com/is/image/ColumbiaSportswear2/1594731_231_lf1?wid=768&hei=806&v=1687354768",
      name: "Columbia Men's Newton Ridge Plus II Waterproof Hiking Boots",
      price: "$89.99",
      description: "Sturdy hiking boots with a waterproof leather upper and advanced traction outsole.",
      ratings: 4.5,
      measurement: "Size 10",
    },
    {
      id: 15,
      picture: "https://images.journeys.com/images/products/1_604899_FS_ALT1C.JPG",
      name: "Crocs Men's Classic Clogs",
      price: "$49.99",
      description: "Comfortable and lightweight clogs with a ventilated design and Croslite foam cushioning.",
      ratings: 4.3,
      measurement: "Size 9.5",
    },
    {
      id: 16,
      picture: "https://i.ytimg.com/vi/aoZ6tKTNub0/maxresdefault.jpg",
      name: "Dockers Men's Proposal Leather Loafers",
      price: "$59.99",
      description: "Classic loafers with a polished leather upper and cushioned footbed for all-day comfort.",
      ratings: 4.2,
      measurement: "Size 10.5",
    },
    {
      id: 17,
      picture: "https://hip2save.com/wp-content/uploads/2020/02/Mens-Bushacre-2-Leather-Chukka-Boots-1.jpg?fit=1200%2C630&strip=all",
      name: "Clarks Men's Bushacre 2 Chukka Boots",
      price: "$99.99",
      description: "Versatile chukka boots with a suede or leather upper and durable rubber sole.",
      ratings: 4.6,
      measurement: "Size 9",
    },
  ];
export default menCasualShoesData; 