const menWalletsData = [
    {
      id: 1,
      picture: "/images/wallets/1.jpg",
      name: "Tommy Hilfiger Men's Leather Wallet",
      price: "$49.99",
      description: "Genuine leather wallet with multiple card slots and a bill compartment.",
      ratings: 4.5,
      measurement: "4.5 x 3.5 inches",
    },
    {
      id: 2,
      picture: "/images/wallets/2.jpg",
      name: "Fossil Men's Ingram Leather Trifold Wallet",
      price: "$59.99",
      description: "Trifold leather wallet with an ID window, card slots, and a bill compartment.",
      ratings: 4.3,
      measurement: "4.25 x 3.25 inches",
    },
    {
      id: 3,
      picture: "/images/wallets/3.jpg",
      name: "Bellroy Slim Sleeve Leather Wallet",
      price: "$79.99",
      description: "Slim and compact leather wallet with card slots and a hidden bill section.",
      ratings: 4.7,
      measurement: "4 x 3 inches",
    },
    {
      id: 4,
      picture: "/images/wallets/4.jpg",
      name: "Herschel Supply Co. Men's Roy RFID Wallet",
      price: "$39.99",
      description: "RFID-blocking wallet with card slots, a currency sleeve, and a coin pocket.",
      ratings: 4.2,
      measurement: "4.25 x 3.5 inches",
    },
    {
      id: 5,
      picture: "/images/wallets/5.jpg",
      name: "Nautica Men's Leather Slim Bifold Wallet",
      price: "$29.99",
      description: "Slim bifold wallet with card slots, an ID window, and a bill compartment.",
      ratings: 4.4,
      measurement: "4.25 x 3.5 inches",
    },
    {
      id: 6,
      picture: "/images/wallets/6.jpg",
      name: "Levi's Men's Trifold Wallet",
      price: "$34.99",
      description: "Trifold leather wallet with card slots, an ID window, and a currency pocket.",
      ratings: 4.6,
      measurement: "4.25 x 3.25 inches",
    },
    {
      id: 7,
      picture: "/images/wallets/7.jpg",
      name: "Dockers Men's Leather Bifold Wallet",
      price: "$24.99",
      description: "Classic bifold wallet with multiple card slots and a bill compartment.",
      ratings: 4.3,
      measurement: "4.5 x 3.5 inches",
    },
    {
      id: 8,
      picture: "/images/wallets/8.jpg",
      name: "Timberland Men's Leather Trifold Wallet",
      price: "$39.99",
      description: "Trifold leather wallet with multiple card slots and a spacious bill compartment.",
      ratings: 4.8,
      measurement: "4.25 x 3.25 inches",
    },
    {
      id: 9,
      picture: "/images/wallets/9.jpg",
      name: "Calvin Klein Men's Leather Bifold Wallet",
      price: "$49.99",
      description: "Premium leather bifold wallet with card slots and a large bill compartment.",
      ratings: 4.5,
      measurement: "4.5 x 3.5 inches",
    },
    {
      id: 10,
      picture: "/images/wallets/10.jpg",
      name: "Fossil Men's Neel Leather Trifold Wallet",
      price: "$59.99",
      description: "Trifold leather wallet with multiple card slots and a bill compartment.",
      ratings: 4.7,
      measurement: "4.25 x 3.25 inches",
    },
    {
      id: 11,
      picture: "/images/wallets/11.jpg",
      name: "Herschel Supply Co. Men's Charlie RFID Wallet",
      price: "$29.99",
      description: "Slim and compact RFID-blocking wallet with multiple card slots.",
      ratings: 4.4,
      measurement: "4 x 3 inches",
    },
    {
      id: 12,
      picture: "/images/wallets/12.jpg",
      name: "Tommy Hilfiger Men's Leather Bifold Wallet",
      price: "$39.99",
      description: "Classic leather bifold wallet with card slots and a bill compartment.",
      ratings: 4.6,
      measurement: "4.5 x 3.5 inches",
    },
    {
      id: 13,
      picture: "/images/wallets/13.jpg",
      name: "Bellroy Note Sleeve Slim Leather Wallet",
      price: "$89.99",
      description: "Slim and functional leather wallet with card slots, a coin pocket, and a bill sleeve.",
      ratings: 4.8,
      measurement: "4.25 x 3.25 inches",
    },
    {
      id: 14,
      picture: "/images/wallets/14.jpg",
      name: "Nautica Men's Leather Passcase Wallet",
      price: "$34.99",
      description: "Passcase wallet with multiple card slots, an ID window, and a bill compartment.",
      ratings: 4.3,
      measurement: "4.5 x 3.5 inches",
    },
    {
      id: 15,
      picture: "/images/wallets/15.jpg",
      name: "Levi's Men's Extra Capacity Slimfold Wallet",
      price: "$24.99",
      description: "Slimfold wallet with card slots, an ID window, and a spacious bill compartment.",
      ratings: 4.5,
      measurement: "4.25 x 3.5 inches",
    },
  ];
  export default menWalletsData;