const menWalletsData = [
    {
      id: 1,
      picture: "https://m.media-amazon.com/images/I/715S9deS1WL._AC_UL1500_.jpg",
      name: "Tommy Hilfiger Men's Leather Wallet",
      price: "$49.99",
      description: "Genuine leather wallet with multiple card slots and a bill compartment.",
      ratings: 4.5,
      measurement: "4.5 x 3.5 inches",
    },
    {
      id: 2,
      picture: "https://fossil.scene7.com/is/image/FossilPartners/ML3289200_1?$sfcc_fos_hi-res$",
      name: "Fossil Men's Ingram Leather Trifold Wallet",
      price: "$59.99",
      description: "Trifold leather wallet with an ID window, card slots, and a bill compartment.",
      ratings: 4.3,
      measurement: "4.25 x 3.25 inches",
    },
    {
      id: 3,
      picture: "https://m.media-amazon.com/images/I/61q+r4TrrSL._AC_UY1000_.jpg",
      name: "Bellroy Slim Sleeve Leather Wallet",
      price: "$79.99",
      description: "Slim and compact leather wallet with card slots and a hidden bill section.",
      ratings: 4.7,
      measurement: "4 x 3 inches",
    },
    {
      id: 4,
      picture: "https://herschel.com/content/dam/herschel/product-detail-images/RoyCoin-Detail-CoinPocket.jpg",
      name: "Herschel Supply Co. Men's Roy RFID Wallet",
      price: "$39.99",
      description: "RFID-blocking wallet with card slots, a currency sleeve, and a coin pocket.",
      ratings: 4.2,
      measurement: "4.25 x 3.5 inches",
    },
    {
      id: 5,
      picture: "https://i.pinimg.com/736x/3c/04/0b/3c040ba2be211abc10b5f4258939036b.jpg",
      name: "Nautica Men's Leather Slim Bifold Wallet",
      price: "$29.99",
      description: "Slim bifold wallet with card slots, an ID window, and a bill compartment.",
      ratings: 4.4,
      measurement: "4.25 x 3.5 inches",
    },
    {
      id: 6,
      picture: "https://www.shopmyexchange.com/products/images/xlarge/8313547_UWUX.jpg",
      name: "Levi's Men's Trifold Wallet",
      price: "$34.99",
      description: "Trifold leather wallet with card slots, an ID window, and a currency pocket.",
      ratings: 4.6,
      measurement: "4.25 x 3.25 inches",
    },
    {
      id: 7,
      picture: "https://m.media-amazon.com/images/I/81rC039GkWL._AC_UY1100_.jpg",
      name: "Dockers Men's Leather Bifold Wallet",
      price: "$24.99",
      description: "Classic bifold wallet with multiple card slots and a bill compartment.",
      ratings: 4.3,
      measurement: "4.5 x 3.5 inches",
    },
    {
      id: 8,
      picture: "https://images-cdn.ubuy.co.in/635078bdb349c65573215f93-timberland-men-s-leather-passcase-wallet.jpg",
      name: "Timberland Men's Leather Trifold Wallet",
      price: "$39.99",
      description: "Trifold leather wallet with multiple card slots and a spacious bill compartment.",
      ratings: 4.8,
      measurement: "4.25 x 3.25 inches",
    },
    {
      id: 9,
      picture: "https://m.media-amazon.com/images/I/81r5XyihBoL._AC_UY1100_.jpg",
      name: "Calvin Klein Men's Leather Bifold Wallet",
      price: "$49.99",
      description: "Premium leather bifold wallet with card slots and a large bill compartment.",
      ratings: 4.5,
      measurement: "4.5 x 3.5 inches",
    },
    {
      id: 10,
      picture: "https://fossil.scene7.com/is/image/FossilPartners/ML3869014_1?$sfcc_fos_large$",
      name: "Fossil Men's Neel Leather Trifold Wallet",
      price: "$59.99",
      description: "Trifold leather wallet with multiple card slots and a bill compartment.",
      ratings: 4.7,
      measurement: "4.25 x 3.25 inches",
    },
    {
      id: 11,
      picture: "https://m.media-amazon.com/images/I/91UEuLJ7yyL._AC_UY1100_.jpg",
      name: "Herschel Supply Co. Men's Charlie RFID Wallet",
      price: "$29.99",
      description: "Slim and compact RFID-blocking wallet with multiple card slots.",
      ratings: 4.4,
      measurement: "4 x 3 inches",
    },
    {
      id: 12,
      picture: "https://m.media-amazon.com/images/I/81dZ6k6TjpS._AC_UY1100_.jpg",
      name: "Tommy Hilfiger Men's Leather Bifold Wallet",
      price: "$39.99",
      description: "Classic leather bifold wallet with card slots and a bill compartment.",
      ratings: 4.6,
      measurement: "4.5 x 3.5 inches",
    },
    {
      id: 13,
      picture: "https://m.media-amazon.com/images/S/aplus-seller-content-images-us-east-1/ATVPDKIKX0DER/A3CSAYA4MI36OG/31ce3ded-9aac-456c-9ba3-511297580659.__CR0,0,300,300_PT0_SX300_V1___.jpeg",
      name: "Bellroy Note Sleeve Slim Leather Wallet",
      price: "$89.99",
      description: "Slim and functional leather wallet with card slots, a coin pocket, and a bill sleeve.",
      ratings: 4.8,
      measurement: "4.25 x 3.25 inches",
    },
    {
      id: 14,
      picture: "https://m.media-amazon.com/images/I/613OBI1GHOL._AC_UY1100_.jpg",
      name: "Nautica Men's Leather Passcase Wallet",
      price: "$34.99",
      description: "Passcase wallet with multiple card slots, an ID window, and a bill compartment.",
      ratings: 4.3,
      measurement: "4.5 x 3.5 inches",
    },
    {
      id: 15,
      picture: "https://cdn.packhacker.com/2019/07/b8384a4d-bellroy-note-sleeve-in-essex-england-1.jpg?auto=compress&auto=format&w=1200&h=630&fit=crop",
      name: "Levi's Men's Extra Capacity Slimfold Wallet",
      price: "$24.99",
      description: "Slimfold wallet with card slots, an ID window, and a spacious bill compartment.",
      ratings: 4.5,
      measurement: "4.25 x 3.5 inches",
    },
  ];
  export default menWalletsData;