const ladiesLeatherShoesData = [
    {
      id: 1,
      image: "shoe1.jpg",
      name: "Classic Leather Pumps",
      price: "$99.99",
      description: "The Classic Leather Pumps are timeless and versatile shoes that can be dressed up or down. They are made from premium leather and feature a pointed toe, a comfortable heel, and a sleek design.",
      ratings: 4.8,
      measurement: "Available Sizes: 5-10",
    },
    {
      id: 2,
      image: "shoe2.jpg",
      name: "Leather Ballet Flats",
      price: "$79.99",
      description: "The Leather Ballet Flats are a comfortable and stylish option for everyday wear. They are crafted from soft leather and feature a round toe, a flexible sole, and a cushioned insole for all-day comfort.",
      ratings: 4.5,
      measurement: "Available Sizes: 5-11",
    },
    {
      id: 3,
      image: "shoe3.jpg",
      name: "Ankle Strap Sandals",
      price: "$89.99",
      description: "The Ankle Strap Sandals are chic and trendy shoes that add a touch of sophistication to any outfit. They are made from genuine leather and feature a slim ankle strap, a block heel, and a cushioned footbed.",
      ratings: 4.7,
      measurement: "Available Sizes: 5-10",
    },
    {
      id: 4,
      image: "shoe4.jpg",
      name: "Leather Wedge Sandals",
      price: "$109.99",
      description: "The Leather Wedge Sandals are stylish and comfortable shoes that provide both height and support. They are crafted from high-quality leather and feature a wedge heel, an adjustable ankle strap, and a cushioned insole.",
      ratings: 4.6,
      measurement: "Available Sizes: 5-11",
    },
    {
      id: 5,
      image: "shoe5.jpg",
      name: "Leather Loafers",
      price: "$99.99",
      description: "The Leather Loafers are classic and sophisticated shoes that can be worn for both formal and casual occasions. They are made from genuine leather and feature a slip-on design, a comfortable fit, and a durable sole.",
      ratings: 4.4,
      measurement: "Available Sizes: 5-10",
    },
    {
      id: 6,
      image: "shoe6.jpg",
      name: "Leather Oxford Shoes",
      price: "$119.99",
      description: "The Leather Oxford Shoes are a timeless and elegant choice for any wardrobe. They are crafted from premium leather and feature a lace-up closure, a low heel, and a cushioned insole for added comfort.",
      ratings: 4.3,
      measurement: "Available Sizes: 5-11",
    },
    {
      id: 7,
      image: "shoe7.jpg",
      name: "Leather Slingback Heels",
      price: "$109.99",
      description: "The Leather Slingback Heels are stylish and versatile shoes that can be dressed up or down. They are made from genuine leather and feature a slingback strap, a pointed toe, and a comfortable heel height.",
      ratings: 4.7,
      measurement: "Available Sizes: 5-10",
    },
    {
      id: 8,
      image: "shoe8.jpg",
      name: "Leather Espadrille Sandals",
      price: "$89.99",
      description: "The Leather Espadrille Sandals are a perfect choice for summer outings. They are crafted from soft leather and feature an espadrille sole, a strappy design, and a cushioned footbed for all-day comfort.",
      ratings: 4.5,
      measurement: "Available Sizes: 5-11",
    },
    {
      id: 9,
      image: "shoe9.jpg",
      name: "Leather Mules",
      price: "$79.99",
      description: "The Leather Mules are effortless and stylish shoes that can be worn for various occasions. They are made from genuine leather and feature a slip-on design, a comfortable fit, and a low heel for easy wearability.",
      ratings: 4.2,
      measurement: "Available Sizes: 5-10",
    },
    {
      id: 10,
      image: "shoe10.jpg",
      name: "Leather Chelsea Boots",
      price: "$129.99",
      description: "The Leather Chelsea Boots are a must-have for any wardrobe. They are crafted from high-quality leather and feature a classic Chelsea boot silhouette, elastic side panels, and a durable sole for long-lasting wear.",
      ratings: 4.6,
      measurement: "Available Sizes: 5-11",
    },
    {
      id: 11,
      image: "shoe11.jpg",
      name: "Leather Suede Pumps",
      price: "$89.99",
      description: "The Leather Suede Pumps are elegant and sophisticated shoes that add a touch of luxury to any outfit. They are made from premium leather suede and feature a pointed toe, a slim heel, and a cushioned insole.",
      ratings: 4.4,
      measurement: "Available Sizes: 5-10",
    },
]
export default ladiesLeatherShoesData;