const menFormalShoesData = [
    {
      id: 1,
      picture: "/images/formal-shoes/1.jpg",
      name: "Allen Edmonds Park Avenue",
      price: "$395.00",
      description: "Classic cap-toe oxfords with a leather upper and leather sole.",
      ratings: 4.8,
      measurement: "Size 10",
    },
    {
      id: 2,
      picture: "/images/formal-shoes/2.jpg",
      name: "Church's Consul Oxford",
      price: "$650.00",
      description: "Elegant oxfords with a polished leather upper and Goodyear welt construction.",
      ratings: 4.7,
      measurement: "Size 9.5",
    },
    {
      id: 3,
      picture: "/images/formal-shoes/3.jpg",
      name: "Gucci Horsebit Loafer",
      price: "$790.00",
      description: "Luxurious loafers with a leather upper, signature horsebit detail, and leather sole.",
      ratings: 4.6,
      measurement: "Size 10.5",
    },
    {
      id: 4,
      picture: "/images/formal-shoes/4.jpg",
      name: "John Lobb City II",
      price: "$1,300.00",
      description: "Handcrafted oxfords with a calfskin leather upper and single leather sole.",
      ratings: 4.9,
      measurement: "Size 9",
    },
    {
      id: 5,
      picture: "/images/formal-shoes/5.jpg",
      name: "Crockett & Jones Hallam",
      price: "$625.00",
      description: "Timeless oxfords with a sleek design, leather upper, and leather sole.",
      ratings: 4.7,
      measurement: "Size 10",
    },
    {
      id: 6,
      picture: "/images/formal-shoes/6.jpg",
      name: "Salvatore Ferragamo Gancini Bit Loafer",
      price: "$680.00",
      description: "Stylish loafers with a leather upper, signature Gancini bit detail, and leather sole.",
      ratings: 4.5,
      measurement: "Size 9.5",
    },
    {
      id: 7,
      picture: "/images/formal-shoes/7.jpg",
      name: "Berluti Alessandro Whole-Cut Oxford",
      price: "$1,950.00",
      description: "Exquisite whole-cut oxfords with a patinated leather upper and leather sole.",
      ratings: 4.8,
      measurement: "Size 10.5",
    },
    {
      id: 8,
      picture: "/images/formal-shoes/8.jpg",
      name: "Edward Green Chelsea",
      price: "$1,100.00",
      description: "Sleek chelsea boots with a leather upper, elastic side panels, and leather sole.",
      ratings: 4.6,
      measurement: "Size 9",
    },
    {
      id: 9,
      picture: "/images/formal-shoes/9.jpg",
      name: "Hugo Boss Dressapp",
      price: "$295.00",
      description: "Modern oxfords with a leather upper, plain toe, and leather sole.",
      ratings: 4.4,
      measurement: "Size 10",
    },
    {
      id: 10,
      picture: "/images/formal-shoes/10.jpg",
      name: "Alden Plain Toe Blucher",
      price: "$565.00",
      description: "Classic blucher shoes with a cordovan leather upper and leather sole.",
      ratings: 4.7,
      measurement: "Size 9.5",
    },
    {
      id: 11,
      picture: "/images/formal-shoes/11.jpg",
      name: "Magnanni Marco",
      price: "$375.00",
      description: "Sophisticated oxfords with a burnished leather upper and leather sole.",
      ratings: 4.5,
      measurement: "Size 10",
    },
    {
      id: 12,
      picture: "/images/formal-shoes/12.jpg",
      name: "Mezlan Oxford",
      price: "$425.00",
      description: "Elegant oxfords with a leather upper, brogue details, and leather sole.",
      ratings: 4.3,
      measurement: "Size 9.5",
    },
    {
      id: 13,
      picture: "/images/formal-shoes/13.jpg",
      name: "Bally Scribe Albano",
      price: "$550.00",
      description: "Refined oxfords with a calfskin leather upper and leather sole.",
      ratings: 4.6,
      measurement: "Size 10.5",
    },
    {
      id: 14,
      picture: "/images/formal-shoes/14.jpg",
      name: "Carmina Shoemaker Quarter Brogue",
      price: "$620.00",
      description: "Handcrafted brogue shoes with a leather upper, wingtip design, and leather sole.",
      ratings: 4.8,
      measurement: "Size 9",
    },
    {
      id: 15,
      picture: "/images/formal-shoes/15.jpg",
      name: "Corthay Arca",
      price: "$1,950.00",
      description: "Artisanal oxfords with a patinated leather upper and signature red leather sole.",
      ratings: 4.7,
      measurement: "Size 10",
    },
  ];
export default menFormalShoesData;  