const passportCoverData = [
    {
      id: 1,
      picture: "passport-cover1.jpg",
      name: "Leather Passport Cover",
      price: "$19.99",
      description: "The Leather Passport Cover is a stylish and functional accessory for your travel needs. It is made from high-quality leather and features multiple card slots, a passport pocket, and a secure closure.",
      ratings: 4.7,
      measurement: "Dimensions: 5.5 x 4 inches",
    },
    {
      id: 2,
      picture: "passport-cover2.jpg",
      name: "Minimalist Passport Holder",
      price: "$14.99",
      description: "The Minimalist Passport Holder is a sleek and compact option for keeping your passport safe. It is crafted from durable materials and features a slim design with a clear ID window and a card slot.",
      ratings: 4.5,
      measurement: "Dimensions: 5.25 x 3.75 inches",
    },
    {
      id: 3,
      picture: "passport-cover3.jpg",
      name: "RFID Blocking Passport Wallet",
      price: "$24.99",
      description: "The RFID Blocking Passport Wallet provides extra security for your passport and cards. It is made from RFID-blocking material to protect against electronic theft and features multiple card slots and a passport pocket.",
      ratings: 4.8,
      measurement: "Dimensions: 5.75 x 4.25 inches",
    },
    {
      id: 4,
      picture: "passport-cover4.jpg",
      name: "Leather Travel Document Holder",
      price: "$29.99",
      description: "The Leather Travel Document Holder is designed to keep all your travel essentials organized. It is crafted from genuine leather and features multiple card slots, a passport pocket, and additional compartments for tickets and documents.",
      ratings: 4.6,
      measurement: "Dimensions: 6 x 4.5 inches",
    },
    {
      id: 5,
      picture: "passport-cover5.jpg",
      name: "Personalized Passport Cover",
      price: "$22.99",
      description: "The Personalized Passport Cover adds a personal touch to your travel accessories. It is customizable with your initials and is made from high-quality materials, offering protection and style for your passport.",
      ratings: 4.7,
      measurement: "Dimensions: 5.5 x 4 inches",
    },
    {
      id: 6,
      picture: "passport-cover6.jpg",
      name: "Vintage Leather Passport Holder",
      price: "$34.99",
      description: "The Vintage Leather Passport Holder is a classic accessory that exudes elegance. It is made from premium leather with a distressed finish, featuring a passport pocket, card slots, and a pen holder.",
      ratings: 4.9,
      measurement: "Dimensions: 5.75 x 4.25 inches",
    },
    {
      id: 7,
      picture: "passport-cover7.jpg",
      name: "Passport Cover with Luggage Tag",
      price: "$27.99",
      description: "The Passport Cover with Luggage Tag is a matching set that adds a touch of style to your travel gear. The passport cover features multiple card slots, a passport pocket, and the luggage tag ensures easy identification of your bags.",
      ratings: 4.6,
      measurement: "Dimensions: 5.5 x 4 inches (Passport Cover)",
    },
    {
      id: 8,
      picture: "passport-cover8.jpg",
      name: "Slim Passport Sleeve",
      price: "$17.99",
      description: "The Slim Passport Sleeve is a minimalist and lightweight option for protecting your passport. It is made from durable materials and offers a snug fit for your passport, ensuring it stays secure during your travels.",
      ratings: 4.4,
      measurement: "Dimensions: 5.25 x 3.75 inches",
    },
    {
      id: 9,
      picture: "passport-cover9.jpg",
      name: "Passport Cover with RFID Blocking",
      price: "$26.99",
      description: "The Passport Cover with RFID Blocking technology provides an extra layer of security for your personal information. It is designed to prevent unauthorized scanning of your passport and cards, keeping your identity safe.",
      ratings: 4.8,
      measurement: "Dimensions: 5.75 x 4.25 inches",
    },
    {
      id: 10,
      picture: "passport-cover10.jpg",
      name: "Passport Holder with Zipper",
      price: "$21.99",
      description: "The Passport Holder with Zipper offers added security and organization for your travel essentials. It features a zippered closure to keep your passport and cards safe, along with additional compartments for tickets and cash.",
      ratings: 4.5,
      measurement: "Dimensions: 5.5 x 4 inches",
    },
  ];
export default passportCoverData; 