const menBeltsData = [
    {
      id: 1,
      picture: "https://m.media-amazon.com/images/I/81AmYQYzjpL._AC_UY1100_.jpg",
      name: "Levi's Men's Reversible Leather Belt",
      price: "$29.99",
      description: "Genuine leather belt with a reversible design and a stylish buckle.",
      ratings: 4.5,
      measurement: "Available in various sizes",
    },
    {
      id: 2,
      picture: "https://www.ubuy.com.bd/productimg/?image=aHR0cHM6Ly9tLm1lZGlhLWFtYXpvbi5jb20vaW1hZ2VzL0kvODFrQm5mb3NnUUwuX0FDX1VMMTUwMF8uanBn.jpg",
      name: "Tommy Hilfiger Men's Leather Belt",
      price: "$39.99",
      description: "Premium leather belt with a classic design and a polished buckle.",
      ratings: 4.3,
      measurement: "Available in various sizes",
    },
    {
      id: 3,
      picture: "https://i5.walmartimages.com/asr/d5b23e2e-5700-4e9a-acda-9e8534c4a753_1.58e17ed0194567a989885a2191a2d969.jpeg?odnHeight=450&odnWidth=450&odnBg=ffffff",
      name: "Fossil Men's Braided Leather Belt",
      price: "$49.99",
      description: "Braided leather belt with a vintage-inspired look and a metal buckle.",
      ratings: 4.7,
      measurement: "Available in various sizes",
    },
    {
      id: 4,
      picture: "https://m.media-amazon.com/images/I/41FsrFpvFDL.jpg",
      name: "Dockers Men's Casual Leather Belt",
      price: "$24.99",
      description: "Casual leather belt with a single-prong buckle and a distressed finish.",
      ratings: 4.2,
      measurement: "Available in various sizes",
    },
    {
      id: 5,
      picture: "https://m.media-amazon.com/images/I/41MspEpcgoL._AC_SY400_.jpg",
      name: "Nautica Men's Feather Edge Leather Belt",
      price: "$34.99",
      description: "Feather edge leather belt with a polished harness buckle and a tapered design.",
      ratings: 4.4,
      measurement: "Available in various sizes",
    },
    {
      id: 6,
      picture: "https://slimages.macysassets.com/is/image/MCY/products/0/optimized/16014120_fpx.tif?op_sharpen=1&wid=700&hei=855&fit=fit,1",
      name: "Calvin Klein Men's Leather Belt",
      price: "$39.99",
      description: "Classic leather belt with a brushed nickel buckle and a sleek design.",
      ratings: 4.6,
      measurement: "Available in various sizes",
    },
    {
      id: 7,
      picture: "https://slimages.macysassets.com/is/image/MCY/products/0/optimized/9050460_fpx.tif?op_sharpen=1&wid=700&hei=855&fit=fit,1",
      name: "Hugo Boss Men's Dress Leather Belt",
      price: "$59.99",
      description: "Dress leather belt with a textured strap and a polished pin buckle.",
      ratings: 4.3,
      measurement: "Available in various sizes",
    },
    {
      id: 8,
      picture: "https://m.media-amazon.com/images/I/71l96xZ4opL._AC_UL1500_.jpg",
      name: "Timberland Men's Casual Leather Belt",
      price: "$29.99",
      description: "Casual leather belt with a distressed strap and a square buckle.",
      ratings: 4.8,
      measurement: "Available in various sizes",
    },
    {
      id: 9,
      picture: "https://www.houseoffraser.co.uk/images/imgzoom/94/94509705_xxl.jpg",
      name: "Polo Ralph Lauren Men's Leather Belt",
      price: "$49.99",
      description: "Premium leather belt with a debossed logo and a polished roller buckle.",
      ratings: 4.5,
      measurement: "Available in various sizes",
    },
    {
      id: 10,
      picture: "https://image.menswearhouse.com/is/image/TMW/MW40_8WRK_03_COLE_HAAN_BROWN_SET?wid=1200&hei=627",
      name: "Cole Haan Men's Dress Belt",
      price: "$59.99",
      description: "Dress belt with a smooth leather strap and a polished buckle.",
      ratings: 4.7,
      measurement: "Available in various sizes",
    },
    {
      id: 11,
      picture: "https://m.media-amazon.com/images/I/41xIaVQ-ukL.jpg",
      name: "Kenneth Cole Reaction Men's Leather Belt",
      price: "$34.99",
      description: "Leather belt with a contrast stitched edge and a brushed nickel buckle.",
      ratings: 4.4,
      measurement: "Available in various sizes",
    },
    {
      id: 12,
      picture: "https://cdn.shopify.com/s/files/1/0547/0201/products/am0am10665_bds_800x.jpg?v=1681834417",
      name: "Herschel Supply Co. Men's Casual Belt",
      price: "$24.99",
      description: "Casual belt with a woven strap and a metal roller buckle.",
      ratings: 4.6,
      measurement: "Available in various sizes",
    },
    {
      id: 13,
      picture: "https://cdn-images.farfetch-contents.com/19/60/19/85/19601985_44318025_600.jpg",
      name: "Diesel Men's Leather Belt",
      price: "$39.99",
      description: "Stylish leather belt with a distressed strap and a logo-engraved buckle.",
      ratings: 4.8,
      measurement: "Available in various sizes",
    },
    {
      id: 14,
      picture: "https://img.guess.com/image/upload/f_auto,q_auto,fl_strip_profile,w_800,c_scale/v1/NA/Style/ECOMM/65068-BLK",
      name: "Guess Men's Reversible Leather Belt",
      price: "$34.99",
      description: "Reversible leather belt with a polished plaque buckle and an embossed logo.",
      ratings: 4.3,
      measurement: "Available in various sizes",
    },
    {
      id: 15,
      picture: "https://m.media-amazon.com/images/I/71xcfRENz3L._AC_UY1100_.jpg",
      name: "Tommy Bahama Men's Leather Belt",
      price: "$29.99",
      description: "Casual leather belt with a distressed strap and a metal buckle.",
      ratings: 4.5,
      measurement: "Available in various sizes",
    },
  ];
  export default menBeltsData;