const mensSandalLeatherData = [
  {
    id: 1,
    picture: "https://i0.wp.com/www.pristineshop.com.bd/wp-content/uploads/2023/04/0734-2.jpg?ssl=1",
    name: "Classic Brown Leather Sandals",
    price: 49.99,
    description: "Premium quality classic brown leather sandals for men.",
    ratings: 4.5,
    measurement: "Available in sizes 7-12",
  },
  {
    id: 2,
    picture: "https://www.oliverbonas.com/static/media/catalog/product/1/5/1533583_2.jpg",
    name: "Black Leather Fisherman Sandals",
    price: 39.99,
    description: "Stylish black leather fisherman sandals with adjustable straps.",
    ratings: 4.2,
    measurement: "Available in sizes 6-11",
  },
  {
    id: 3,
    picture: "https://www.adelisaandco.com/cdn/shop/products/CJPF3890.jpg?v=1643840178",
    name: "Tan Leather Slide Sandals",
    price: 34.99,
    description: "Comfortable tan leather slide sandals with cushioned insole.",
    ratings: 4.7,
    measurement: "Available in sizes 8-13",
  },
  {
    id: 4,
    picture: "https://i5.walmartimages.com/asr/f235a238-3aaf-4d6c-a0fa-5049be0df02a.3ddeec9cf8ac0f3ac5e095d809b6a971.jpeg?odnHeight=450&odnWidth=450&odnBg=ffffff",
    name: "Brown Leather Hiking Sandals",
    price: 59.99,
    description: "Durable brown leather hiking sandals for outdoor adventures.",
    ratings: 4.4,
    measurement: "Available in sizes 7-12",
  },
  {
    id: 5,
    picture: "https://m.media-amazon.com/images/I/51xES4oNBbL._AC_SY1000_.jpg",
    name: "Casual Slip-On Leather Sandals",
    price: 29.99,
    description: "Casual slip-on leather sandals with a relaxed and comfortable fit.",
    ratings: 4.0,
    measurement: "Available in sizes 6-11",
  },
  {
    id: 6,
    picture: "https://sgfm.elcorteingles.es/SGFM/dctm/MEDIA03/202303/01/00103054805365____4__516x640.jpg",
    name: "Black Leather Strappy Sandals",
    price: 44.99,
    description: "Fashionable black leather strappy sandals with a trendy design.",
    ratings: 4.3,
    measurement: "Available in sizes 7-12",
  },
  {
    id: 7,
    picture: "https://www.iconsofsurf.co.uk/cdn/shop/products/301ALTWS-1_400x.jpg?v=1643801704",
    name: "Classic Tan Leather Sandals",
    price: 49.99,
    description: "Classic tan leather sandals with a timeless and versatile style.",
    ratings: 4.6,
    measurement: "Available in sizes 8-13",
  },
  {
    id: 8,
    picture: "https://www.mensjournal.com/.image/t_share/MTk2MTM2ODAzMTY2ODU2MzM3/2-reef-draftsmen.jpg",
    name: "Brown Leather Flip-Flop Sandals",
    price: 19.99,
    description: "Casual brown leather flip-flop sandals for everyday wear.",
    ratings: 3.9,
    measurement: "Available in sizes 6-11",
  },
  {
    id: 9,
    picture: "https://images-cdn.ubuy.co.in/634599f32ee01e3add207753-visionreast-mens-leather-sandals-outdoor.jpg",
    name: "Sports Leather Sandals",
    price: 54.99,
    description: "Sports-inspired leather sandals with adjustable straps and cushioned insole.",
    ratings: 4.5,
    measurement: "Available in sizes 7-12",
  },
  {
    id: 10,
    picture: "https://expresshub.com.bd/Images/Product/8613445/8613445_2_87c3b323-342a-441b-922b-8c8edd9b2ae2_.webp",
    name: "Comfortable Slip-On Sandals",
    price: 39.99,
    description: "Comfortable slip-on sandals with soft leather and contoured footbed.",
    ratings: 4.2,
    measurement: "Available in sizes 6-11",
  },
  {
    id: 11,
    picture: "https://m.media-amazon.com/images/I/715ER2ieEVL._AC_UY1000_.jpg",
    name: "Stylish Leather Thong Sandals",
    price: 29.99,
    description: "Stylish leather thong sandals with a trendy and fashionable design.",
    ratings: 4.3,
    measurement: "Available in sizes 7-12",
  },
  {
    id: 12,
    picture: "https://m.media-amazon.com/images/I/61vgqJ6kStL._AC_UY1000_.jpg",
    name: "Brown Leather Outdoor Sandals",
    price: 59.99,
    description: "Durable brown leather outdoor sandals for hiking and other outdoor activities.",
    ratings: 4.4,
    measurement: "Available in sizes 7-12",
  },
  {
    id: 13,
    picture: "https://static-01.daraz.com.bd/p/3227da7315c2db7fed127ae029ca0c75.jpg_750x750.jpg_.webp_.webp",
    name: "Casual Leather Sandals",
    price: 34.99,
    description: "Casual leather sandals with a comfortable fit for everyday use.",
    ratings: 4.1,
    measurement: "Available in sizes 6-11",
  },
  {
    id: 14,
    picture: "https://i5.walmartimages.com/asr/9826c124-dffd-4a3e-a918-d54ddac9599c.498a4c8d6d3b76e173f1e7036b08e2fa.jpeg",
    name: "Black Leather Sport Sandals",
    price: 49.99,
    description: "Black leather sport sandals with adjustable straps and cushioned insole.",
    ratings: 4.7,
    measurement: "Available in sizes 7-12",
  },
  {
    id: 15,
    picture: "https://travelfashiongirlpostphotos.s3.us-east-2.amazonaws.com/2020/Cute+Tan+Sandals/tan-sandals-15.2.jpg",
    name: "Stylish Tan Leather Sandals",
    price: 39.99,
    description: "Stylish tan leather sandals with a trendy and fashionable design.",
    ratings: 4.2,
    measurement: "Available in sizes 8-13",
  },
  {
    id: 16,
    picture: "https://m.media-amazon.com/images/I/61YkbK-tgXL._AC_UF894,1000_QL80_.jpg",
    name: "Brown Leather Beach Sandals",
    price: 29.99,
    description: "Casual brown leather beach sandals for a relaxed and comfortable style.",
    ratings: 4.4,
    measurement: "Available in sizes 6-11",
  },
  {
    id: 17,
    picture: "https://www.beekshop.com/cdn/shop/products/pelican-honey-sandal-womens-beek-1_grande.jpg?v=1673588977",
    name: "Leather Slide Sandals",
    price: 34.99,
    description: "Leather slide sandals with a simple and minimalist design.",
    ratings: 4.0,
    measurement: "Available in sizes 7-12",
  },
  {
    id: 18,
    picture: "https://ssbleather.com/public/uploads/all/V6B3v93XEzqpDuKdGEalaioYsKOfHW3eqpwnIcNO.jpg",
    name: "Black Leather Casual Sandals",
    price: 39.99,
    description: "Black leather casual sandals with a comfortable and versatile style.",
    ratings: 4.3,
    measurement: "Available in sizes 8-13",
  },
  {
    id: 19,
    picture: "https://www.ges-sandals.gr/wp-content/uploads/2019/01/Dermatino-sandali_15T-3.jpg",
    name: "Classic Brown Leather Sandals",
    price: 49.99,
    description: "Classic brown leather sandals with a timeless and versatile style.",
    ratings: 4.6,
    measurement: "Available in sizes 7-12",
  },
  {
    id: 20,
    picture: "https://mardigras.co.in/wp-content/uploads/2022/04/mardi-gras19068-scaled.jpg",
    name: "Tan Leather Flip-Flop Sandals",
    price: 19.99,
    description: "Casual tan leather flip-flop sandals for comfortable everyday wear.",
    ratings: 4.1,
    measurement: "Available in sizes 6-11",
  },
  {
    id: 21,
    picture: "https://www.rosella.co.za/images/products/25637.jpg",
    name: "Tan Leather Flip-Flop Sandals",
    price: 19.99,
    description: "Casual tan leather flip-flop sandals for comfortable everyday wear.",
    ratings: 4.1,
    measurement: "Available in sizes 6-11",
  },
  {
    id: 22,
    picture: "https://www.batabd.com/cdn/shop/products/1_ff9c4dca-a9e6-40f8-9a3d-c5acb058cd6b_1024x1024.jpg?v=1680753031",
    name: "Leather Slingback Sandals",
    price: 44.99,
    description: "Leather slingback sandals with a stylish and elegant design.",
    ratings: 4.5,
    measurement: "Available in sizes 7-12",
  },
]

export default mensSandalLeatherData;
