const menJacketsData = [
    {
      id: 1,
      picture: "/images/jackets/1.jpg",
      name: "Classic Black Leather Jacket",
      price: "$199.99",
      description: "A timeless black leather jacket with a sleek design and premium quality.",
      ratings: 4.5,
      measurement: "Available in various sizes",
    },
    {
      id: 2,
      picture: "/images/jackets/2.jpg",
      name: "Biker Style Leather Jacket",
      price: "$249.99",
      description: "A stylish biker-style leather jacket with zipper details and a rugged look.",
      ratings: 4.3,
      measurement: "Available in various sizes",
    },
    {
      id: 3,
      picture: "/images/jackets/3.jpg",
      name: "Brown Distressed Leather Jacket",
      price: "$219.99",
      description: "A brown distressed leather jacket with a vintage-inspired look and feel.",
      ratings: 4.7,
      measurement: "Available in various sizes",
    },
    {
      id: 4,
      picture: "/images/jackets/4.jpg",
      name: "Slim Fit Leather Jacket",
      price: "$189.99",
      description: "A slim fit leather jacket with a modern and tailored silhouette.",
      ratings: 4.2,
      measurement: "Available in various sizes",
    },
    {
      id: 5,
      picture: "/images/jackets/5.jpg",
      name: "Aviator Style Leather Jacket",
      price: "$279.99",
      description: "An aviator-style leather jacket with a fur collar and a classic design.",
      ratings: 4.4,
      measurement: "Available in various sizes",
    },
    {
      id: 6,
      picture: "/images/jackets/6.jpg",
      name: "Vintage Bomber Leather Jacket",
      price: "$239.99",
      description: "A vintage-style bomber leather jacket with ribbed cuffs and a zip closure.",
      ratings: 4.6,
      measurement: "Available in various sizes",
    },
    {
      id: 7,
      picture: "/images/jackets/7.jpg",
      name: "Dark Brown Leather Jacket",
      price: "$209.99",
      description: "A dark brown leather jacket with a rugged yet sophisticated look.",
      ratings: 4.3,
      measurement: "Available in various sizes",
    },
    {
      id: 8,
      picture: "/images/jackets/8.jpg",
      name: "Cafe Racer Leather Jacket",
      price: "$199.99",
      description: "A classic cafe racer leather jacket with a minimalist and timeless design.",
      ratings: 4.8,
      measurement: "Available in various sizes",
    },
    {
      id: 9,
      picture: "/images/jackets/9.jpg",
      name: "Shearling Collar Leather Jacket",
      price: "$229.99",
      description: "A leather jacket with a cozy shearling collar for added warmth and style.",
      ratings: 4.5,
      measurement: "Available in various sizes",
    },
    {
      id: 10,
      picture: "/images/jackets/10.jpg",
      name: "Motorcycle Style Leather Jacket",
      price: "$259.99",
      description: "A motorcycle-style leather jacket with quilted panels and a tough look.",
      ratings: 4.7,
      measurement: "Available in various sizes",
    },
    {
      id: 11,
      picture: "/images/jackets/11.jpg",
      name: "Vintage Brown Leather Jacket",
      price: "$219.99",
      description: "A vintage brown leather jacket with a distressed finish and a classic style.",
      ratings: 4.4,
      measurement: "Available in various sizes",
    },
    {
      id: 12,
      picture: "/images/jackets/12.jpg",
      name: "Hooded Leather Jacket",
      price: "$189.99",
      description: "A hooded leather jacket with a casual and versatile design.",
      ratings: 4.6,
      measurement: "Available in various sizes",
    },
    {
      id: 13,
      picture: "/images/jackets/13.jpg",
      name: "Red Leather Biker Jacket",
      price: "$239.99",
      description: "A bold red leather biker jacket with zipper accents and a statement look.",
      ratings: 4.8,
      measurement: "Available in various sizes",
    },
    {
      id: 14,
      picture: "/images/jackets/14.jpg",
      name: "Distressed Moto Leather Jacket",
      price: "$219.99",
      description: "A distressed moto leather jacket with a worn-in look and a rebellious vibe.",
      ratings: 4.3,
      measurement: "Available in various sizes",
    },
    {
      id: 15,
      picture: "/images/jackets/15.jpg",
      name: "Tan Leather Jacket",
      price: "$199.99",
      description: "A stylish tan leather jacket with a versatile and modern design.",
      ratings: 4.5,
      measurement: "Available in various sizes",
    },
  ];
  export default menJacketsData;