const menJacketsData = [
    {
      id: 1,
      picture: "https://www.lucaccileather.com/wp-content/uploads/2022/04/Hayden-Black-Biker-Jacket-1.jpg",
      name: "Classic Black Leather Jacket",
      price: "$199.99",
      description: "A timeless black leather jacket with a sleek design and premium quality.",
      ratings: 4.5,
      measurement: "Available in various sizes",
    },
    {
      id: 2,
      picture: "https://leatherbangladesh.com.bd/wp-content/uploads/2022/10/FB_IMG_1663371511895-600x600.jpg",
      name: "Biker Style Leather Jacket",
      price: "$249.99",
      description: "A stylish biker-style leather jacket with zipper details and a rugged look.",
      ratings: 4.3,
      measurement: "Available in various sizes",
    },
    {
      id: 3,
      picture: "https://assets.vogue.com/photos/6400b53b1de49cf499716253/3:4/w_1280%2Cc_limit/slide_%2520(13).jpg",
      name: "Brown Distressed Leather Jacket",
      price: "$219.99",
      description: "A brown distressed leather jacket with a vintage-inspired look and feel.",
      ratings: 4.7,
      measurement: "Available in various sizes",
    },
    {
      id: 4,
      picture: "https://static-01.daraz.com.bd/p/6524e1aba339899823334266a8cf49f6.jpg_720x720.jpg_.webp",
      name: "Slim Fit Leather Jacket",
      price: "$189.99",
      description: "A slim fit leather jacket with a modern and tailored silhouette.",
      ratings: 4.2,
      measurement: "Available in various sizes",
    },
    {
      id: 5,
      picture: "https://be70132adc3274767577-527aa459f97c8d6fb369f63eccbe6b99.ssl.cf1.rackcdn.com/images/variant/large/scin-13037-distressedbrown.jpg",
      name: "Aviator Style Leather Jacket",
      price: "$279.99",
      description: "An aviator-style leather jacket with a fur collar and a classic design.",
      ratings: 4.4,
      measurement: "Available in various sizes",
    },
    {
      id: 6,
      picture: "https://cdn.shoplightspeed.com/shops/625505/files/15472890/670x871x2/jamin-leather-vintage-brown-leather-a2-bomber-jack.jpg",
      name: "Vintage Bomber Leather Jacket",
      price: "$239.99",
      description: "A vintage-style bomber leather jacket with ribbed cuffs and a zip closure.",
      ratings: 4.6,
      measurement: "Available in various sizes",
    },
    {
      id: 7,
      picture: "https://5.imimg.com/data5/HK/QR/MY-68594208/men-leather-jackets-500x500.jpg",
      name: "Dark Brown Leather Jacket",
      price: "$209.99",
      description: "A dark brown leather jacket with a rugged yet sophisticated look.",
      ratings: 4.3,
      measurement: "Available in various sizes",
    },
    {
      id: 8,
      picture: "https://www.urbanrider.co.uk/media/catalog/product/cache/008f5b54fa8158acf29751501a361c85/c/a/cafe_racer_leather_jacket_brown_02.jpg",
      name: "Cafe Racer Leather Jacket",
      price: "$199.99",
      description: "A classic cafe racer leather jacket with a minimalist and timeless design.",
      ratings: 4.8,
      measurement: "Available in various sizes",
    },
    {
      id: 9,
      picture: "https://superstarjackets.com/wp-content/uploads/2022/03/Mens-Slim-Fit-Shearling-Fur-Collar-Brown-Leather-Jacket-2.jpg",
      name: "Shearling Collar Leather Jacket",
      price: "$229.99",
      description: "A leather jacket with a cozy shearling collar for added warmth and style.",
      ratings: 4.5,
      measurement: "Available in various sizes",
    },
    {
      id: 10,
      picture: "https://cdn.shopify.com/s/files/1/0422/8897/1929/products/size5-15858424838689-232-4sr-jacket-cool-evo-1_2020-04-21_13-42-58_H1EQsLohpk_1200x630.jpg?v=1593698681",
      name: "Motorcycle Style Leather Jacket",
      price: "$259.99",
      description: "A motorcycle-style leather jacket with quilted panels and a tough look.",
      ratings: 4.7,
      measurement: "Available in various sizes",
    },
    {
      id: 11,
      picture: "https://i.etsystatic.com/27370735/r/il/4caccf/4943747673/il_fullxfull.4943747673_3lxe.jpg",
      name: "Vintage Brown Leather Jacket",
      price: "$219.99",
      description: "A vintage brown leather jacket with a distressed finish and a classic style.",
      ratings: 4.4,
      measurement: "Available in various sizes",
    },
    {
      id: 12,
      picture: "https://5.imimg.com/data5/BM/PU/RA/SELLER-4547156/leather-jacket-500x500.jpg",
      name: "Hooded Leather Jacket",
      price: "$189.99",
      description: "A hooded leather jacket with a casual and versatile design.",
      ratings: 4.6,
      measurement: "Available in various sizes",
    },
    {
      id: 13,
      picture: "https://ae01.alicdn.com/kf/Hc905cb93300f4bea80f126f28c78e48dk.jpg_640x640Q90.jpg_.webp",
      name: "Red Leather Biker Jacket",
      price: "$239.99",
      description: "A bold red leather biker jacket with zipper accents and a statement look.",
      ratings: 4.8,
      measurement: "Available in various sizes",
    },
    {
      id: 14,
      picture: "https://i.ebayimg.com/images/g/KNYAAOSwDwNeZ-ZY/s-l1200.jpg",
      name: "Distressed Moto Leather Jacket",
      price: "$219.99",
      description: "A distressed moto leather jacket with a worn-in look and a rebellious vibe.",
      ratings: 4.3,
      measurement: "Available in various sizes",
    },
    {
      id: 15,
      picture: "https://www.leathercompany.co.uk/images/vegetable-tanned-leather-biker-jacket-tan-mcqueen-p2295-10395_image.jpg",
      name: "Tan Leather Jacket",
      price: "$199.99",
      description: "A stylish tan leather jacket with a versatile and modern design.",
      ratings: 4.5,
      measurement: "Available in various sizes",
    },
  ];
  export default menJacketsData;