const corporateGiftsData = [
    {
      id: 1,
      picture: "corporate-gift1.jpg",
      name: "Leather Keychain",
      price: "$9.99",
      description: "The Leather Keychain is a stylish and practical corporate gift. It is made from high-quality leather and features a durable metal ring to hold keys. Customization options are available.",
      ratings: 4.7,
      measurement: "Dimensions: 3.5 x 1.5 inches",
    },
    {
      id: 2,
      picture: "corporate-gift2.jpg",
      name: "Leather Portfolio",
      price: "$39.99",
      description: "The Leather Portfolio is a professional and sophisticated gift for employees or clients. It is crafted from premium leather and features multiple pockets, a notepad slot, and a pen holder.",
      ratings: 4.5,
      measurement: "Dimensions: 13 x 10 inches",
    },
    {
      id: 3,
      picture: "corporate-gift3.jpg",
      name: "Leather Card Holder",
      price: "$14.99",
      description: "The Leather Card Holder is a sleek and compact gift option. It is made from genuine leather and can hold multiple cards. Customization with a company logo is available.",
      ratings: 4.8,
      measurement: "Dimensions: 4 x 2.75 inches",
    },
    {
      id: 4,
      picture: "corporate-gift4.jpg",
      name: "Leather Mouse Pad",
      price: "$19.99",
      description: "The Leather Mouse Pad adds a touch of elegance to any office setup. It is crafted from premium leather and provides a smooth surface for precise mouse movements. Customization options are available.",
      ratings: 4.6,
      measurement: "Dimensions: 9 x 7.5 inches",
    },
    {
      id: 5,
      picture: "corporate-gift5.jpg",
      name: "Leather Notebook",
      price: "$24.99",
      description: "The Leather Notebook is a sophisticated and practical gift option. It features a genuine leather cover, refillable pages, and a pen loop. Customization with a company logo is available.",
      ratings: 4.7,
      measurement: "Dimensions: 6 x 8.5 inches",
    },
    {
      id: 6,
      picture: "corporate-gift6.jpg",
      name: "Leather Coaster Set",
      price: "$29.99",
      description: "The Leather Coaster Set is a stylish and functional gift for the office or home. It includes a set of four coasters made from high-quality leather, with a holder for convenient storage.",
      ratings: 4.9,
      measurement: "Dimensions: 4 x 4 inches (each coaster)",
    },
    {
      id: 7,
      picture: "corporate-gift7.jpg",
      name: "Leather Desk Organizer",
      price: "$34.99",
      description: "The Leather Desk Organizer helps keep workspaces tidy and organized. It features multiple compartments for holding pens, business cards, and other essentials. Customization options are available.",
      ratings: 4.6,
      measurement: "Dimensions: 8 x 4.5 inches",
    },
    {
      id: 8,
      picture: "corporate-gift8.jpg",
      name: "Leather Travel Wallet",
      price: "$26.99",
      description: "The Leather Travel Wallet is a practical and stylish gift for frequent travelers. It features multiple pockets for passports, cards, and currency, as well as a zippered pocket for added security.",
      ratings: 4.4,
      measurement: "Dimensions: 9 x 4.5 inches",
    },
    {
      id: 9,
      picture: "corporate-gift9.jpg",
      name: "Leather Business Card Holder",
      price: "$17.99",
      description: "The Leather Business Card Holder is a professional accessory for networking and business meetings. It is made from premium leather and can hold multiple business cards.",
      ratings: 4.8,
      measurement: "Dimensions: 3.75 x 2.5 inches",
    },
    {
      id: 10,
      picture: "corporate-gift10.jpg",
      name: "Leather Desk Pad",
      price: "$21.99",
      description: "The Leather Desk Pad adds style and functionality to any workspace. It provides a smooth writing surface and protects the desk from scratches. Customization options are available.",
      ratings: 4.5,
      measurement: "Dimensions: 24 x 16 inches",
    },
  ];
export default corporateGiftsData;  