const corporateGiftsData = [
    {
      id: 1,
      picture: "https://oxandpine.com/cdn/shop/products/2023-02-0612.40.00.jpg?v=1681411436",
      name: "Leather Keychain",
      price: "$9.99",
      description: "The Leather Keychain is a stylish and practical corporate gift. It is made from high-quality leather and features a durable metal ring to hold keys. Customization options are available.",
      ratings: 4.7,
      measurement: "Dimensions: 3.5 x 1.5 inches",
    },
    {
      id: 2,
      picture: "https://www.leatherneo.com/cdn/shop/products/IMG_1554.jpg?v=1634847127",
      name: "Leather Portfolio",
      price: "$39.99",
      description: "The Leather Portfolio is a professional and sophisticated gift for employees or clients. It is crafted from premium leather and features multiple pockets, a notepad slot, and a pen holder.",
      ratings: 4.5,
      measurement: "Dimensions: 13 x 10 inches",
    },
    {
      id: 3,
      picture: "https://crazyhorsecraft.com/cdn/shop/products/Credit-business-card-holder-leather-orange-6.jpg?v=1529994793",
      name: "Leather Card Holder",
      price: "$14.99",
      description: "The Leather Card Holder is a sleek and compact gift option. It is made from genuine leather and can hold multiple cards. Customization with a company logo is available.",
      ratings: 4.8,
      measurement: "Dimensions: 4 x 2.75 inches",
    },
    {
      id: 4,
      picture: "https://www.holtzleather.com/cdn/shop/products/The-Architect-Personalized-Fine-Leather-Mouse-Pad-Mousepad-Holtz-Leather-Co-image12_2048x.jpg?v=1581088893",
      name: "Leather Mouse Pad",
      price: "$19.99",
      description: "The Leather Mouse Pad adds a touch of elegance to any office setup. It is crafted from premium leather and provides a smooth surface for precise mouse movements. Customization options are available.",
      ratings: 4.6,
      measurement: "Dimensions: 9 x 7.5 inches",
    },
    {
      id: 5,
      picture: "https://images.squarespace-cdn.com/content/v1/5349ba13e4b095a3fb0ba65c/12818602-9239-4fa8-b412-945ea05b1072/Harber-London-Leather-Notebook-Cover.jpeg",
      name: "Leather Notebook",
      price: "$24.99",
      description: "The Leather Notebook is a sophisticated and practical gift option. It features a genuine leather cover, refillable pages, and a pen loop. Customization with a company logo is available.",
      ratings: 4.7,
      measurement: "Dimensions: 6 x 8.5 inches",
    },
    {
      id: 6,
      picture: "https://image.made-in-china.com/202f0j00ihKzkjscrqbG/Business-Logo-Reversible-Leather-Coaster-Set-Table-Coasters-with-Holder.webp",
      name: "Leather Coaster Set",
      price: "$29.99",
      description: "The Leather Coaster Set is a stylish and functional gift for the office or home. It includes a set of four coasters made from high-quality leather, with a holder for convenient storage.",
      ratings: 4.9,
      measurement: "Dimensions: 4 x 4 inches (each coaster)",
    },
    {
      id: 7,
      picture: "https://images-cdn.ubuy.co.in/633b226ebed76170fe323267-kingfom-pu-leather-desktop-organizer-for.jpg",
      name: "Leather Desk Organizer",
      price: "$34.99",
      description: "The Leather Desk Organizer helps keep workspaces tidy and organized. It features multiple compartments for holding pens, business cards, and other essentials. Customization options are available.",
      ratings: 4.6,
      measurement: "Dimensions: 8 x 4.5 inches",
    },
    {
      id: 8,
      picture: "https://www.galenleather.com/cdn/shop/products/leather-wallet-insert-for-travelers-notebook-passport-size-crazy-horse-brown_050ae44f-c3dd-4b4d-8a73-fee2c0eabd4b_2000x.jpg?v=1617640864",
      name: "Leather Travel Wallet",
      price: "$26.99",
      description: "The Leather Travel Wallet is a practical and stylish gift for frequent travelers. It features multiple pockets for passports, cards, and currency, as well as a zippered pocket for added security.",
      ratings: 4.4,
      measurement: "Dimensions: 9 x 4.5 inches",
    },
    {
      id: 9,
      picture: "https://m.media-amazon.com/images/I/71SXL7-ZuuL._AC_UY1100_.jpg",
      name: "Leather Business Card Holder",
      price: "$17.99",
      description: "The Leather Business Card Holder is a professional accessory for networking and business meetings. It is made from premium leather and can hold multiple business cards.",
      ratings: 4.8,
      measurement: "Dimensions: 3.75 x 2.5 inches",
    },
    {
      id: 10,
      picture: "https://www.galenleather.com/cdn/shop/products/leather-desk-pad_3600x.jpg?v=1617635447",
      name: "Leather Desk Pad",
      price: "$21.99",
      description: "The Leather Desk Pad adds style and functionality to any workspace. It provides a smooth writing surface and protects the desk from scratches. Customization options are available.",
      ratings: 4.5,
      measurement: "Dimensions: 24 x 16 inches",
    },
  ];
export default corporateGiftsData;  